spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productprofile?useSSL=false
    username: root
    password: sqlroot!

    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#JPA Settings
    jpa.hibernate.ddl_auto: create
